# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 120)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: #5F9EA0;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"    height: 60px;\n"
"    border: 2px groove rgb(47,79,79);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0,0,0,50);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.d_btn_close = QtWidgets.QPushButton(Dialog)
        self.d_btn_close.setGeometry(QtCore.QRect(310, 80, 81, 31))
        self.d_btn_close.setObjectName("d_btn_close")
        self.procces = QtWidgets.QLabel(Dialog)
        self.procces.setGeometry(QtCore.QRect(10, 32, 381, 41))
        self.procces.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.procces.setObjectName("procces")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 381, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title.setObjectName("title")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ожидание"))
        self.d_btn_close.setText(_translate("Dialog", "Закрыть"))
        self.procces.setText(_translate("Dialog", "Ожидание"))
        self.title.setText(_translate("Dialog", "Ожидание"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
